var boss_rates_country={init:function(){var ratesel_mode=$('#ratesel_mode').val();var ratesel_details=$("#ratesel_details");var ratesel_amount=$("#ratesel_amount");var ratesel_submit=$('#ratesel_submit');function show_rates(){$('#ratesel_rate_details').show();$('#ratesel_plan_details').hide();$("#ratesel_rates_menu_item").addClass('selected');$("#ratesel_plans_menu_item").removeClass('selected');}
function show_plans(){$('#ratesel_rate_details').hide();$('#ratesel_plan_details').show();$("#ratesel_rates_menu_item").removeClass('selected');$("#ratesel_plans_menu_item").addClass('selected');}
function show_plan_details(){$('#ratesel_plan_details_rates').show();$('#ratesel_plan_details_dests').hide();}
function show_dest_details(){$('#ratesel_plan_details_rates').hide();$('#ratesel_plan_details_dests').show();}
function init_after_partial_load(){var ratesel_plan=$("#ratesel_plans_menu_item");if(ratesel_plan.length){ratesel_plan.click(show_plans);$("#ratesel_rates_menu_item").click(show_rates);$('#ratesel_learn_more_plans').click(show_plans);$('#ratesel_plan_details_rates_dests').click(show_dest_details);$('#ratesel_plan_details_dests_back').click(show_plan_details);}}
function country_changed_redirect(){var c=ratesel_submit.attr('data-country');if(c==null||c=="")window.location.href=boss_culture+"/rates";else window.location.href=boss_culture+"/rates/"+c;}
function country_changed_ajax(){var c=ratesel_submit.attr('data-country');$.ajax({cache:false,type:"GET",url:boss_culture+"/rates/ajax/"+c,data:{mode:ratesel_mode},success:function(data){ratesel_details.html('');ratesel_details.html(data);ratesel_amount=$("#ratesel_amount");ratesel_amount.change(calculate_minutes_and_cookie);calculate_minutes(ratesel_amount.val());if(ratesel_mode!='F')ratesel_amount.selectOrDie();init_after_partial_load();window.location.hash=window.location.hash;},error:function(){}});}
function calculate_minutes(a){a=a*100;var o;_.forEach($('[data-rate]'),function(obj){o=$(obj);o.html(Math.floor(a/parseFloat(o.attr('data-rate')))+" min");});}
function calculate_minutes_and_cookie(){$.cookie('calculator_amount',ratesel_amount.val(),{expires:100,path:'/'});calculate_minutes(ratesel_amount.val());}
if(ratesel_mode=='C'){ratesel_amount.change(calculate_minutes_and_cookie);calculate_minutes(ratesel_amount.val());}else if(ratesel_mode=='R'){ratesel_submit.click(country_changed_redirect);ratesel_amount.change(calculate_minutes_and_cookie);calculate_minutes(ratesel_amount.val());}else if(ratesel_mode=='F'){ratesel_submit.click(country_changed_ajax);country_changed_ajax();}else if(ratesel_mode=='S'){ratesel_submit.click(country_changed_ajax);country_changed_ajax();}
init_after_partial_load();}};$(boss_rates_country.init);